# Generated by Django 5.1.6 on 2025-03-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappv0', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'managed': False},
        ),
    ]
